import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackGround from "./components/particleBg/BackGround";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <BackGround>
          {/* <h2 className="text-7xl absolut z-10 flex flex-col justify-center items-center text-white font-bold">Hello</h2> */}
          <main className="relative pt-16 md:pt-20 z-10">
           {children} 
          </main>
          
        </BackGround>
        
      </body>
    </html>
  );
}
