import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackGround from "./components/particleBg/BackGround";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050505]`}>
        
        {/* ব্যাকগ্রাউন্ডকে আলাদা লেয়ার হিসেবে রাখুন */}
        <div className="fixed inset-0 z-0">
           <BackGround />
        </div>

        {/* কন্টেন্টকে এর উপরে রাখুন */}
        <main className="relative z-10 pt-6 md:pt-10">
           {children} 
        </main>
        
      </body>
    </html>
  );
}
