import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import BackGround from "./components/particleBg/BackGround";
import InitialLoader from "./components/InitialLoader";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "taharim hasan",
  description: "Generated by create next app",
  icons: {
    icon: "/myportfolioimg.jpg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-[#050505]`}>
        
        
        <InitialLoader/>
        {/* Background */}
        <div className="fixed inset-0 z-0">
           <BackGround />
        </div>

        <main className="relative z-10 pt-6 md:pt-10">
           {children} 
        </main>
        
      </body>
    </html>
  );
}
